name: Deploy HTML files to S3

on:
  push:
    branches:
      - main
    paths:
      - 'kyleallbright_webpage/index.html'
      - 'kyleallbright_webpage/giphygenerator.html'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_ACCESS_SECRET }}
          aws-region: us-east-1

      - name: Upload index.html to S3 (if present)
        if: ${{ hashFiles('index.html') != '' }}
        run: aws s3 cp kyleallbright_webpage/index.html s3://${{ secrets.S3_BUCKET_ARN }}/index.html --acl public-read --region us-east-1

      - name: Upload giphygenerator.html to S3 (if present)
        if: ${{ hashFiles('giphygenerator.html') != '' }}
        run: aws s3 cp kyleallbright_webpage/giphygenerator.html s3://${{ secrets.S3_BUCKET_ARN }}/giphygenerator.html --acl public-read --region us-east-1
